service: serverless-intv-demo

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:

  # # PROXY
  # main:
  #   handler: ${env:PROXY_HANDLER_PATH}
  #   events:
  #     - http:
  #         method: ANY
  #         path: /
  #     - http:
  #         method: ANY
  #         path: '{proxy+}'

  # USER
  getUsers:
    handler: ${env:HANDLER_PATH}.handlersUser.getUsers
    events:
      - http:
          method: GET
          path: /users
  getMe:
    handler: ${env:HANDLER_PATH}.handlersUser.getMe
    events:
      - http:
          method: GET
          path: /users/me
  getUserById:
    handler: ${env:HANDLER_PATH}.handlersUser.getUserById
    events:
      - http:
          method: GET
          path: /users/{id}
  createUser:
    handler: ${env:HANDLER_PATH}.handlersUser.createUser
    events:
      - http:
          method: POST
          path: /users
  updateUser:
    handler: ${env:HANDLER_PATH}.handlersUser.updateUser
    events:
      - http:
          method: PATCH
          path: /users/{id}
  removeUser:
    handler: ${env:HANDLER_PATH}.handlersUser.removeUser
    events:
      - http:
          method: DELETE
          path: /users/{id}

  # AUTH
  signUp:
    handler: ${env:HANDLER_PATH}.handlersAuth.signUp
    events:
      - http:
          method: POST
          path: /auth/signup
  signIn:
    handler: ${env:HANDLER_PATH}.handlersAuth.signIn
    events:
      - http:
          method: POST
          path: /auth/signin
  logOut:
    handler: ${env:HANDLER_PATH}.handlersAuth.logOut
    events:
      - http:
          method: GET
          path: /auth/logout
  refreshTokens:
    handler: ${env:HANDLER_PATH}.handlersAuth.refreshTokens
    events:
      - http:
          method: GET
          path: /auth/refresh-tokens






